[Variables]
Theme = Light
Language = Russian
Cleaner = "C:\Program Files\CCleaner\CCleaner64.exe"
DirectionAudioVisualizer = 1
Scale = 1
ScaleTarsh           = (1*#Scale#)
ScaleBar             = (1*#Scale#)
ScaleAudioControl    = (1.5*#Scale#)
ScaleAudioVisualizer = (1*#Scale#)
ScaleInfo            = (1*#Scale#)
ScaleClock           = (1*#Scale#)
ScaleSettings        = (1*#Scale#)

[StyleFont]
Antialias = 1
FontFace = a_FuturicaLt